# Generated by Django 5.1.6 on 2025-02-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MySkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(max_length=100, unique=True)),
                ("skill_larning_period", models.CharField(max_length=100)),
                ("skill_level", models.IntegerField()),
                ("skill_description", models.TextField()),
                ("skill_image", models.ImageField(upload_to="images/")),
            ],
            options={
                "db_table": "my_skill",
            },
        ),
    ]
