# Generated by Django 5.1.6 on 2025-02-23 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="myskill",
            old_name="skill_larning_period",
            new_name="skill_learning_period",
        ),
    ]
