# Generated by Django 5.1.6 on 2025-02-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio_app",
            "0002_rename_skill_larning_period_myskill_skill_learning_period",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MyQualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qualification_name", models.CharField(max_length=100, unique=True)),
                ("qualification_acquisition_date", models.DateField()),
            ],
            options={
                "db_table": "my_qualification",
            },
        ),
    ]
