# Generated by Django 5.1.6 on 2025-02-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0003_myqualification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myqualification",
            name="qualification_acquisition_date",
            field=models.CharField(max_length=100),
        ),
    ]
