# Generated by Django 5.1.6 on 2025-03-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0005_app"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                ("location", models.CharField(max_length=100)),
                ("education", models.CharField(max_length=200)),
                ("about_me", models.TextField()),
                ("profile_image", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
