# Generated by Django 5.1.6 on 2025-04-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0006_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hobby", "趣味"),
                            ("dev", "開発備忘録"),
                            ("other", "その他"),
                        ],
                        max_length=50,
                    ),
                ),
                ("image", models.ImageField(upload_to="blog_images/")),
                ("content", models.TextField()),
                ("excerpt", models.TextField(blank=True, max_length=300)),
            ],
        ),
    ]
