# Generated by Django 5.1.6 on 2025-04-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0008_delete_blogpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="blog",
            field=models.URLField(blank=True, verbose_name="Blog"),
        ),
        migrations.AddField(
            model_name="profile",
            name="github",
            field=models.URLField(blank=True, verbose_name="GitHub"),
        ),
        migrations.AddField(
            model_name="profile",
            name="hobbies",
            field=models.TextField(blank=True, verbose_name="趣味・人柄エピソード"),
        ),
        migrations.AddField(
            model_name="profile",
            name="interests",
            field=models.TextField(
                blank=True, verbose_name="興味・関心・今後挑戦したいこと"
            ),
        ),
    ]
